.github/workflows/codeql-analysis.yml

Automated check for javascript code for security vulnerability. I only enabled checking for javascript, we can enable c++ and python later if need be

proposal: Add CodeQL security analysis

---

.vscode/settings.json
gulpfile.js
package.json
packages/nlu/package.json
packages/nlu/src/index.ts
packages/nlu/src/stan/api.ts
packages/nlu/src/stan/http-typings.ts
packages/nlu/src/stan/index.ts
packages/nlu/src/stan/validation/schemas.ts
scripts/gulp.package.js
yarn.lock

fix(api): no need for min 1 context

---

.gitignore
.vscode/launch.json
gulpfile.js
package.json
packages/nlu/package.json
packages/nlu/src/index.ts
packages/nlu/src/stan/config.ts
packages/nlu/src/stan/index.ts
scripts/gulp.config.js

Super helpfull DX feature to debug.

feat: nlu server can take a config file path at CLI and override the rest of CLI

---

packages/nlu/src/index.ts
packages/nlu/src/stan/api.ts
packages/nlu/src/stan/config.ts
packages/nlu/src/stan/index.ts

feat(cli): log filters param is an array

---

packages/nlu/src/engine/engine/training-pipeline.ts

Description incoming. I opened the PR to make sure I don't forget this fix. It's a note to myself.

fix(training): progress now won't skip steps

---

packages/bitfan/src/services/bp-provider/stan-provider.ts

chore(bitfan): log error when theres one

---

.github/workflows/bitfan.yml
packages/e2e/current_scores/bpds-intent.json
packages/e2e/current_scores/bpds-slots.json
packages/e2e/current_scores/bpds-spell.json
packages/e2e/current_scores/clinc150.json
packages/e2e/src/index.ts
packages/lang-server/src/download.ts

chore(gh): use local lang server in gh checks + update test results to run in dimension 100

---

packages/nlu-client/package.json
packages/nlu-client/src/typings/sdk.d.ts
packages/nlu-server/src/application/errors.ts
packages/nlu-server/src/application/training-queue.ts

feat(nlu-server): calling training twice with same payload results in HTTP 409; training already started

---

packages/nlu-server/src/infrastructure/training-repo/db-training-repo.ts

fix(nlu-server): no maximum size for trainset in database

---

packages/nlu-client/src/typings/sdk.d.ts
packages/nlu-engine/src/engine/entities/duckling-extractor/duckling-client.ts
packages/nlu-engine/src/engine/entities/duckling-extractor/duckling-extractor.test.ts
packages/nlu-engine/src/engine/entities/duckling-extractor/index.ts
packages/nlu-engine/src/engine/entities/duckling-extractor/typings.ts
packages/nlu-engine/src/engine/entities/dummy-system-extractor.ts
packages/nlu-engine/src/engine/initialize-tools.ts
packages/nlu-engine/src/engine/training-process-pool/error-handler.ts
packages/nlu-engine/src/engine/training-process-pool/process-entry-point.ts
packages/nlu-engine/src/engine/typings.ts
packages/nlu-engine/src/errors.ts
packages/nlu-engine/src/index.ts
packages/nlu-engine/src/typings.d.ts
packages/nlu-server/src/application/training-queue.ts

feat: duckling throws errors that are typed in nlu-server's API

---

packages/lang-client/src/client.ts
packages/lang-client/src/validation.test.ts
packages/lang-client/src/validation.ts
packages/nlu-client/src/client.ts
packages/nlu-client/src/validation.test.ts
packages/nlu-client/src/validation.ts

chore(nlu-client): refactor client so it throws meaningful errors if it needs to

---

packages/nlu-engine/src/engine/training-process-pool/index.ts
packages/worker/src/process-pool.ts
packages/worker/src/worker-pool/index.ts
packages/worker/src/worker-pool/scheduler.ts
packages/worker/src/worker-pool/worker.ts

**wip**
@michaelmass let me know if this works better

fix(worker): do not reuse a process if it exited since last usage

---

packages/nlu-engine/src/engine/index.ts
packages/nlu-engine/src/engine/intents/oos-intent-classfier.ts
packages/nlu-engine/src/index.ts
packages/nlu-engine/src/typings.d.ts
packages/nlu-server/src/bootstrap/config.ts
packages/nlu-server/src/bootstrap/make-engine.ts

feat(nlu-engine): rm legacy election support

---

packages/nlu-client/src/typings/hints.d.ts
packages/nlu-client/src/typings/http.d.ts
packages/nlu-client/src/typings/sdk.d.ts
packages/nlu-engine/src/engine/hints/c_000.ts
packages/nlu-engine/src/engine/hints/c_001.ts
packages/nlu-engine/src/engine/hints/c_002.ts
packages/nlu-engine/src/engine/hints/hints-pipeline.ts
packages/nlu-engine/src/engine/hints/id.ts
packages/nlu-engine/src/hints.d.ts
packages/nlu-engine/src/model-id-service.ts
packages/nlu-engine/src/typings.d.ts
packages/nlu-engine/src/utils/half-md5.ts
packages/nlu-server/src/api/http.ts
packages/nlu-server/src/api/index.ts
packages/nlu-server/src/application/errors.ts
packages/nlu-server/src/application/index.ts
packages/nlu-server/src/infrastructure/hints-repo/in-mem-repo.ts
packages/nlu-server/src/infrastructure/hints-repo/typings.ts

chore: return actual progress in hints computation

---

packages/nlu-engine/src/engine/linting/linting-pipeline.ts
packages/nlu-engine/src/typings.d.ts
packages/nlu-server/src/application/index.ts
packages/nlu-server/src/bootstrap/make-application.ts
packages/nlu-server/src/infrastructure/linting-repo/db-linting-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/db-model-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/in-mem-linting-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/index.ts
packages/nlu-server/src/infrastructure/linting-repo/typings.ts

implementation of the database repository

chore: added database linting repository

---

packages/nlu-engine/src/engine/entities/list-entity-model.ts
packages/nlu-engine/src/engine/entities/list-extractor.test.ts
packages/nlu-engine/src/engine/intents/intent-vocab.test.ts
packages/nlu-engine/src/engine/linting/e_000.test.ts
packages/nlu-engine/src/engine/linting/e_000.ts
packages/nlu-engine/src/engine/training-pipeline.ts
packages/nlu-engine/src/engine/typings.ts
packages/nlu-engine/src/linting.d.ts

This is issue indicates that some tokens in an utterance where tagged as a slot even if they don't match any of the slot's entity.
Ex: `"I live in the [province of Quebec](user_country)"` will raise an error with code `e_000` because the slot `user_country` is of type `country` and  tokens `"province of Quebec"` is not an instance of entity `country`.

feat: initial implementation of e_000

---

packages/logger/src/logger.ts
packages/nlu-engine/src/engine/language/language-provider.ts
packages/nlu-engine/src/engine/language/legacy-lang-client.ts

Allows branch `cloud` to be used with [currently hosted lang-server](https://lang-01.botpress.io/info)

chore(nlu-engine): allow nlu-engine to keep working using older versions of lang-server

---

packages/nlu-e2e/src/assertions.ts
packages/nlu-e2e/src/index.ts
packages/nlu-e2e/src/ls-tests.ts
packages/nlu-e2e/src/run-tests.ts
packages/nlu-e2e/src/tests/index.ts
packages/nlu-e2e/src/tests/lang-detection.ts
packages/nlu-e2e/src/tests/model-lifecycle.ts
packages/nlu-e2e/src/tests/prediction.ts
packages/nlu-e2e/src/tests/training.ts
packages/nlu-e2e/src/typings.ts

small refac that allows:
- running only desired tests
- listing available tests

chore(e2e): allow running only desired tests from cli

---

.vscode/launch.json
packages/nlu-e2e/src/assertions.ts
packages/nlu-e2e/src/tests/index.ts
packages/nlu-e2e/src/tests/lang-detection.ts
packages/nlu-e2e/src/tests/linting.ts
packages/nlu-e2e/src/tests/model-lifecycle.ts
packages/nlu-e2e/src/tests/prediction.ts
packages/nlu-e2e/src/tests/training.ts
packages/nlu-e2e/src/utils.ts
packages/nlu-engine/src/engine/linting/e_000.ts
packages/nlu-server/src/api/validation/schemas.ts
packages/nlu-server/src/application/linting-queue/lint-handler.ts

chore(e2e): added few tests for linting + fix e_000 to handle slot any

---

packages/nlu-server/src/api/index.ts
packages/nlu-server/src/application/app-observer.ts
packages/nlu-server/src/application/index.ts
packages/nlu-server/src/telemetry/metric/meter.ts

chore(nlu-server): added prometheus metric to keep track of model loading time

---

packages/nlu-e2e/src/run-tests.ts
packages/nlu-server/src/infrastructure/model-repo/fs-model-repo.ts

fix(nlu-server): ensure forward slashes in app id wont break fs model repo

---

packages/lang-server/src/config.ts
packages/lang-server/src/download.ts
packages/lang-server/src/index.ts
packages/lang-server/src/typings.d.ts
packages/logger/src/config.ts
packages/logger/src/formatters/text.ts
packages/logger/src/index.ts
packages/logger/src/logger.test.ts
packages/logger/src/logger.ts
packages/logger/src/typings.ts
packages/nlu-cli/src/parameters/lang-server.ts
packages/nlu-cli/src/parameters/nlu-server.ts
packages/nlu-e2e/src/ls-tests.ts
packages/nlu-e2e/src/run-tests.ts
packages/nlu-server/src/bootstrap/config.ts
packages/nlu-server/src/index.ts
packages/nlu-server/src/typings.d.ts

chore(nlu-cli): log level is now an enum instead of a number

---

packages/lang-server/src/index.ts
packages/lang-server/src/uncaught-errors.ts
packages/logger/src/config.ts
packages/logger/src/formatters/text.ts
packages/logger/src/typings.ts
packages/nlu-server/src/index.ts
packages/nlu-server/src/uncaught-errors.ts

chore: added process hooks to catch unhandled rejections and exceptions with proper logging

---

.github/actions/setup-e2e/action.yml
.github/workflows/e2e.yml

chore(gh): enable Duckling in e2e tests

---

packages/nlu-client/src/typings/linting.d.ts
packages/nlu-engine/src/engine/intents/oos-intent-classfier.ts
packages/nlu-engine/src/engine/linting/definitions.ts
packages/nlu-engine/src/engine/linting/e_000.test.ts
packages/nlu-engine/src/engine/linting/e_000.ts
packages/nlu-engine/src/engine/linting/e_001.ts
packages/nlu-engine/src/engine/linting/e_002.ts
packages/nlu-engine/src/engine/linting/e_003.ts
packages/nlu-engine/src/engine/linting/e_004.test.ts
packages/nlu-engine/src/engine/linting/e_004.ts
packages/nlu-engine/src/engine/linting/linting-pipeline.ts
packages/nlu-engine/src/engine/linting/w_000.ts
packages/nlu-engine/src/engine/training-pipeline.ts
packages/nlu-engine/src/engine/utterance/utterance.ts
packages/nlu-engine/src/linting.d.ts

chore(engine): added error for duplicated, trailing and leading spaces

---

packages/nlu-client/src/client.ts
packages/nlu-client/src/typings/http.d.ts
packages/nlu-client/src/typings/index.d.ts
packages/nlu-e2e/src/assertions.ts
packages/nlu-e2e/src/tests/linting.ts
packages/nlu-e2e/src/utils.ts
packages/nlu-server/src/api/index.ts
packages/nlu-server/src/api/validation/schemas.ts
packages/nlu-server/src/api/validation/validate.ts
packages/nlu-server/src/application/errors.ts
packages/nlu-server/src/application/index.ts
packages/nlu-server/src/application/linting-queue/index.ts
packages/nlu-server/src/application/linting-queue/lint-task-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/db-linting-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/in-mem-linting-repo.ts
packages/nlu-server/src/infrastructure/linting-repo/typings.ts

seems like a big change, but its not

feat: linting speed is part of linting's id and must be provided by path param

---

packages/nlu-server/src/application/index.ts
packages/nlu-server/src/bootstrap/documentation.ts
packages/nlu-server/src/infrastructure/model-repo/db-model-repo.ts
packages/nlu-server/src/infrastructure/model-repo/fs-model-repo.ts
packages/nlu-server/src/infrastructure/model-repo/typings.ts

chore: cleaner CLI doc + faster get train state query handling

---

packages/nlu-server/src/application/index.ts
packages/nlu-server/src/infrastructure/model-repo/db-model-repo.ts
packages/nlu-server/src/infrastructure/model-repo/fs-model-repo.ts
packages/nlu-server/src/infrastructure/model-repo/typings.ts

this duplication of logic was introduced in last commit
now its fixed

chore: rm major code duplication

---

.dockerignore
.github/workflows/bench.yml
.github/workflows/codestyle.yml
.github/workflows/docker.yml
.github/workflows/e2e.yml
.github/workflows/unit-tests.yml

chore(gh): allow dispatching most gh worflows mannually

---

packages/nlu-cli/readme.md
packages/nlu-cli/src/index.ts

chore(cli): update readme

---

.github/workflows/docker.yml

chore(gh): fix docker gh workflow

---

packages/nlu-engine/src/engine/training-pipeline.ts
packages/nlu-engine/src/utils/watch-dog.ts

make sure to hide white spaces when reviewing

fix(nlu-server): progress watch-dog fully stops when error or done
