botpress/nlu

- packages/nlu/src/engine/engine/predict-pipeline.ts
- packages/nlu/src/engine/engine/utterance/utterance.ts
> fix(engine): spell-checker does not replace entities anymore

- packages/nlu/src/lang-server/index.ts
- packages/nlu/src/stan/index.ts
- packages/nlu/src/utils/logger/formatters/console.ts
Since we are going to have multiple processes running on a single server, it would be nice if we could differentiate the various logs in the console. The logger adds `[Studio]` for all logs studio-related, so this would simply add `[NLU]` to logs. I guess we could add a prefix for the core logs eventually
It doesn't adresses the fact that users on the admin will not see logs from either the studio or the nlu, but we'll see that in the future
> chore(nlu): standardize logs

- .vscode/launch.json
- packages/nlu/src/engine/engine/entities/custom-extractor/index.ts
- packages/nlu/src/engine/engine/entities/custom-extractor/list-extraction.ts
- packages/nlu/src/engine/engine/entities/custom-extractor/multi-thread-extractor.ts
- packages/nlu/src/engine/engine/entities/custom-extractor/serializable-token.ts
- packages/nlu/src/engine/engine/entities/custom-extractor/thread-entry-point.ts
- packages/nlu/src/engine/engine/entities/duckling-extractor/duckling-extractor.test.ts
- packages/nlu/src/engine/engine/entities/duckling-extractor/index.ts
- packages/nlu/src/engine/engine/entities/list-extractor.test.ts
- packages/nlu/src/engine/engine/entities/microsoft-extractor/index.ts
- packages/nlu/src/engine/engine/entities/microsoft-extractor/microsoft-extractor.test.ts
- packages/nlu/src/engine/engine/predict-pipeline.ts
- packages/nlu/src/engine/engine/test-utils/fake-tools.ts
- packages/nlu/src/engine/engine/training-pipeline.ts
- packages/nlu/src/engine/engine/typings.ts
For some bot with few list entities
| - | Cold Training Time (s) |
| ------------- |:-------------:|
| without child threads      | 38.141 |
| with 4 child threads | 12.277 |
There's 4 new threads in the training process:
> chore: run list entity extraction on child threads with progress report

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
The Docker build was failing because the `/nlu/dist/nlu-linux` binary was renamed to `/nlu/dist/nlu-v0_0_7-linux-x64`
I also added automated a GitHub Action that checks if the Docker image builds successfully.
> fix(build): test Docker build

- CHANGELOG.md
- Dockerfile
- package.json
- packages/nlu/package.json
- packages/nlu/src/index.ts
- packages/nlu/src/nlu-server/api.ts
- packages/nlu/src/nlu-server/config.ts
- packages/nlu/src/nlu-server/index.ts
- packages/nlu/src/nlu-server/make-engine.ts
- packages/nlu/src/utils/logger/index.ts
- packages/nlu/src/utils/logger/transports/console.ts
- packages/nlu/src/utils/logger/typings.ts
Basically, if verbose is 4, you have to specify `--log-filter Launcher` to get the debug of filters.
This is done by 2 things:
1. log filter can be `undefined` which results in no filters being applied
2. There is a logger config called `minLevel` which allows to bypass log filters if level is reached. This field is used by Launcher logger.
I took the opportunity to fix a changelog mess I did earlier today + change the env variable `STAN_JSON_CONFIG` by `NLU_SERVER_CONFIG`. This env variable is meant to be used only by the main botpress server anyway.
> fix(logger): launcher debug logs are not displayed by default when verbose is 4

- packages/bitfan/readme.md
- packages/bitfan/src/services/bp-provider/stan-provider.ts
- packages/e2e/src/tests/bpds-intents.ts
- packages/e2e/src/tests/bpds-slots.ts
- packages/e2e/src/tests/bpds-spell.ts
- packages/e2e/src/tests/clinc-intents.ts
This allows running tests against a remote NLU server, or a NLU server that is running locally on another port than 3200
> feat(e2e): configurable NLU server endpoint

- packages/nlu/package.json
- packages/nlu/src/engine/engine/intents/exact-intent-classifier.ts
- packages/nlu/src/engine/engine/predict-pipeline.ts
- packages/nlu/src/engine/engine/slots/slot-tagger.ts
- packages/nlu/src/engine/engine/utterance/utterance.test.ts
- packages/nlu/src/engine/engine/utterance/utterance.ts
This PR should fix [this issue](https://github.com/botpress/botpress/issues/4872) 
Previously if a token had both a slot and an entity, and we had option `slot: 'keep-value'`, then the entity `if` clause was bypassed.
With these new options, slot and entity replacement are mutually exclusive.
> fix: exact matcher now works even with different entities

- packages/bitfan/src/bitfan.d.ts
- packages/bitfan/src/builtin/engines/intent.ts
- packages/bitfan/src/builtin/engines/slot.ts
- packages/bitfan/src/builtin/engines/spell.ts
- packages/bitfan/src/builtin/engines/topic.ts
- packages/bitfan/src/index.ts
- packages/bitfan/src/services/bp-provider/stan-provider.ts
- packages/nlu-client/src/client.ts
- packages/nlu-client/src/typings/index.d.ts
Title pretty much what this PR is about.
This was implemented by asking for appId as method parameter instead of ctor. It is thus only required when truly needed.
> chore(nlu-client): no need for appid when calling the info route

- packages/nlu-engine/src/ml/svm/libsvm/grid-search/index.ts
This PR is part of a sequence of PR's with name `svm training improvement $n` that presents few improvements or combination of improvements as attempts to make training faster and consume less memory.
⚠️⚠️ Do not merge this PR as we first need to compare with other attempts first. ⚠️⚠️
This PR basically removes #88 with commit:
fix(nlu-engine): launch svm trainings one after the other (cec8a7a7b8f28bb567d80050e4f3b3e529d0f558)
There's no real need to run grid-search in serial as the ammount of folds is highly reduced by #91.
On clinc150 using local lang server with dimension 100:
| branch | memory used (mb) | time to train (s) |
|--------|------------------|-------------------|
| master   | ~800             | 101               |
| this   | ~700           | 82 |
On John Doe* using remote …
> svm training improvement 4

- packages/nlu-server/src/infrastructure/model-repo.ts
Model filename looked something like:
`3501c2f56ef0f772.05ee6514b6cded3a.1273.en..model`
which is a bug
> fix(nlu-server): rm consecutive dots in model files extensions

- packages/nlu-client/src/client.ts
- packages/nlu-client/src/typings/http.d.ts
- packages/nlu-client/src/typings/index.d.ts
- packages/nlu-client/src/typings/sdk.d.ts
- packages/nlu-server/examples/api.rest
- packages/nlu-server/src/api/http.ts
- packages/nlu-server/src/api/index.ts
- packages/nlu-server/src/application/distributed-training-queue.ts
- packages/nlu-server/src/application/index.ts
- packages/nlu-server/src/application/training-queue.ts
- packages/nlu-server/src/bootstrap/documentation.ts
- packages/nlu-server/src/infrastructure/model-repo.ts
- packages/nlu-server/src/infrastructure/training-repo/db-training-repo.ts
- packages/nlu-server/src/infrastructure/training-repo/in-memory-training-repo.ts
- packages/nlu-server/src/infrastructure/training-repo/typings.ts
This PR adds route `GET <base>/train` or `GET <base>/train?lang=en`.
It returns all trainings of an app.
> feat(nlu-server): add a route to list all trainings of an app

- .gitignore
- .vscode/settings.json
- package.json
- packages/bitfan/package.json
- packages/e2e/package.json
- packages/lang-server/package.json
- packages/logger/package.json
- packages/nlu-cli/package.json
- packages/nlu-client/package.json
- packages/nlu-engine/package.json
- packages/nlu-server/package.json
- packages/nlu-server/scripts/buildinfo.js
- packages/nlu-server/src/bootstrap/banner.ts
- packages/nlu-server/src/bootstrap/launcher.ts
- packages/nlu-server/src/index.ts
- packages/nlu-server/src/require-json.ts
- packages/nlu-server/src/typings.d.ts
- packages/node-crfsuite/package.json
- packages/node-fasttext/package.json
- packages/node-sentencepiece/package.json
- packages/node-svm/package.json
- packages/worker/package.json
- yarn.lock
This PR contains 2 commits:
1. (8413fbba2fb38c64b5948ee5ae010b1dd6bd20a6) Simply standardize the version of typescript used by all sub packages
2. (7fb5b1b78d07e6ad4395bf5013416d82ca7b1058) Display build information and metadata when booting nlu-server 
For the second one, here's how this works:
1. in a `"postbuild"` script, I generate a `.buildinfo.json` file at the root of nlu-server.
2. when booting nlu-server I try reading this file and if it's present I display its content
3. when packaging in binaries, I make sure `*.json` file at the root of sub packages are included in binary.
Result looks like this:
> chore(dx): log build info on startup in nlu-server

- packages/lang-server/src/app-data.ts
- packages/lang-server/src/download.ts
- packages/lang-server/src/run.ts
- packages/lang-server/src/service/download-manager.ts
- packages/nlu-cli/src/app-data.ts
- packages/nlu-server/src/app-data.ts
this function was probably copied from the core repository, but the function that calls getAppDataPath doesn`t check for APP_DATA_PATH before as the core code does. Added env variable check in this getAppDataPAth so the log makes sense.
> fix: check for APP_DATA_PATH environment variable

- packages/bitfan/src/services/bp-provider/stan-provider.ts
- packages/e2e/tsconfig.json
- packages/locks/tsconfig.json
- packages/nlu-client/jest.config.js
- packages/nlu-client/package.json
- packages/nlu-client/src/client.ts
- packages/nlu-client/src/typings/index.d.ts
- packages/nlu-client/src/validation.test.ts
- packages/nlu-client/src/validation.ts
- packages/nlu-client/tsconfig.json
- packages/nlu-server/package.json
- packages/worker/tsconfig.json
- yarn.lock
This PR allows:
1. to pass an axios config at the nlu-client ctor
2. to access the axios instance of the nlu-client (in read only)
3. won't throw on error status code that are expected and part of a normal nlu-server life-cycle (ex: 404 if no model)
> feat(nlu-client): make nlu-client configurable with an axios config

- packages/nlu-server/src/application/errors.ts
- packages/nlu-server/src/application/index.ts
**WIP**
calling 
- `GET /models`
- `GET /train`
won't return models of invalid specs
calling
- `GET /train/:modelId`
- `GET /predict/:modelId`
- `GET /detect-lang`
with models of invalid spec will return HTTP 400 with message:
`"expected spec hash to be "010effb865ff25fa". target model has spec "4d8dcf8e284f431a"`
> feat(nlu-server): nlu-server won't serve models of invalid spec

- packages/lang-client/package.json
- packages/lang-client/src/client.ts
- packages/lang-client/src/typings.d.ts
- packages/lang-server/src/api/index.ts
- packages/lang-server/src/api/validation/body.ts
- packages/lang-server/src/api/validation/lang-path.ts
The `cloud` branch has already made slight changes to the language server's API, I figured: while we're at it, why not break it even more.
> chore(lang-server): pass language as a path param for all routes

- packages/nlu-server/src/application/training-queue.ts
The `max training` cli option didn't allow the value 0. Setting max training to 0 will disable the training on the nlu server. 
Since the value 0 is falsy in typescript it was using the default value for max training. By removing `pickBy` from lodash it is working properly.
> fix(cli): fix max training parameter to allow the value 0

- packages/nlu-server/src/telemetry/metric/prometheus.ts
The metric `up` should always be 1 so using `signalIsUp` method sets it to 1.
> fix(metrics): fix up metrics to be 1 instead of 0

- .github/workflows/bench.yml
- .github/workflows/e2e.yml
- packages/distributed/src/queues/pg-distributed-queue.ts
this branch only attempts at fixing e2es
> split e2e in 3 different gh jobs

- .vscode/launch.json
I lost about an hour because of that lol...
Basically Knex `"^0.20.1"` only works with node 12 and vscode was using node 16 when debugging
> chore: ensure launch.json uses node 12
